#!/bin/bash

# prepare: func run before testcase
# virt-clone的用例使用raw格式镜像的虚拟机进行测试
#

prepare:type_specific.io-github-autotest-libvirt.libvirt_network_bandwidth.network()
{
      virsh detach-interface --domain $main_vms --type bridge --config
      virsh attach-interface --domain $main_vms --type network --source default --model virtio --mac $mac_nic1 --config
}
restore:type_specific.io-github-autotest-libvirt.libvirt_network_bandwidth.portgroup()
{
      virsh detach-interface --domain $main_vms --type network --config
      virsh attach-interface --domain $main_vms --type bridge --source br0 --model virtio --mac $mac_nic1 --config
}
# Add function in here



# End of function
# start in here
main()
{
	if [ "$1" = "" ]; then
		exit
	fi

	testcase=$1
	class=`echo $1 | cut -d ':' -f1`
	if [ "$class" = "prepare" ]; then
		echo "Run prepare function($1) in $0" 
	elif [ "$class" = "restore" ]; then
		echo "Run restore function($1) in $0" 
	else
		echo "Unknow class($1) in $0" 
	fi

	$testcase 

	if [ "$class" = "prepare" ]; then
		echo "End of prepare function($1) in $0" 
	elif [ "$class" = "restore" ]; then
		echo "End of restore function($1) in $0" 
	else
		echo "End of Unknow class($1) in $0" 
	fi
	echo ""
}

main $1 $2
