#!/bin/bash

#
# Description:
# 	This program can autorun virt-test testcases
#
# Version: 0.5 
# Designed by: Ming.Li
#


CURRENT_DIR=$(pwd)
DEFAULT_CONFIG=$CURRENT_DIR/cfg/base.cfg
DEFAULT_LOG_DIR=$CURRENT_DIR/logs/
DEFAULT_TESTS_DIR=$CURRENT_DIR/tests/
DEFAULT_MODULE_LIST=$CURRENT_DIR/tests/modules_list
DEFAULT_MODULE_FILE_DIR=$CURRENT_DIR/tests/
DEFAULT_SCATTERED_LIST=$CURRENT_DIR/tests/scattered_list
MODE="ANALYSIS"

get_config_key()
{    
    section=$(echo $1 | cut -d '.' -f 1)    
    key=$(echo $1 | cut -d '.' -f 2)    
    sed -n "/\[$section\]/,/\[.*\]/{    
     /^\[.*\]/d    
     /^[ \t]*$/d    
     /^$/d    
     /^#.*$/d    
     s/^[ \t]*$key[ \t]*=[ \t]*\(.*\)[ \t]*/\1/p    
    }" $DEFAULT_CONFIG
}   

VIRTTEST_DIR=$(get_config_key "dir.virt-test")
DEFAULT_RUN_COMMAND=$(get_config_key "command.default_run_cmd")" "
DEFAULT_EXTRA_COMMAND=" "$(get_config_key "command.extra_cmd")
LIBVIRT_EXTRA_COMMAND=" "$(get_config_key "libvirt.extra_cmd")
QEMU_EXTRA_COMMAND=" "$(get_config_key "qemu.extra_cmd")
CURRENT_LOG_PATH=""
CURRENT_CASESLIST_FILE=""
CURRENT_LOG_FILE=""
CURRENT_DETAIL_LOG_FILE=""

debug()
{
	echo "DEBUG:"

	# print env params
	echo -e "\tEnvironments:"
	echo -e "\t\tCURRENT_DIR = $CURRENT_DIR"
	echo -e "\t\tDEFAULT_LOG_DIR = $DEFAULT_LOG_DIR"
	echo -e "\t\tDEFAULT_TESTS_DIR = $DEFAULT_TESTS_DIR"
	echo -e "\t\tDEFAULT_MODULE_FILE_DIR = $DEFAULT_MODULE_FILE_DIR"
	echo -e "\t\tCURRENT_LOG_PATH = $CURRENT_LOG_PATH"

	echo -e "\t\tDEFAULT_CONFIG = $DEFAULT_CONFIG"
	echo -e "\t\tDEFAULT_MODULE_LIST = $DEFAULT_MODULE_LIST"
	echo -e "\t\tDEFAULT_SCATTERED_LIST = $DEFAULT_SCATTERED_LIST"
	echo -e "\t\tCURRENT_CASESLIST_FILE = $CURRENT_CASESLIST_FILE"
	echo -e "\t\tCURRENT_LOG_FILE = $CURRENT_LOG_FILE"
	echo -e "\t\tCURRENT_DETAIL_LOG_FILE = $CURRENT_DETAIL_LOG_FILE"

	# print config data
	echo -e "\tConfig:"
	echo -e "\t\tVIRTEST_DIR = $VIRTTEST_DIR"
	echo -e "\t\tDEFAULT_RUN_COMMAND = $DEFAULT_RUN_COMMAND"
	echo -e "\t\tDEFAULT_EXTRA_COMMAND = $DEFAULT_EXTRA_COMMAND"
	echo -e "\t\tQEMU_EXTRA_COMMAND = $QEMU_EXTRA_COMMAND"
	echo -e "\t\tLIBVIRT_EXTRA_COMMAND = $LIBVIRT_EXTRA_COMMAND"
	echo -e "\n"
}

# Merge repeated parameters
# Priority: testcase`s params > module`s params > default params
# $1: The parameters of the high priority 
# $2: The parameters of the low priority
merge_params()
{
	if [ -z "$1" ] && [ -z "$2" ]; then
		echo ""
		return
	fi
	
	if [ "$1" = "" ]; then
		echo "$2"
		return
	fi

	if [ "$2" = "" ]; then
		echo "$1"
		return
	fi

	final_params="$1"
	params_strs="$2"
	new_params=""

	for i in ${params_strs[@]}
	do
		if [ "${i:0:1}" = "-" ]; then
			if [ "$new_params" != "" ]; then
				final_params="$final_params"" ""$new_params"
				new_params=""
			fi

			echo "$final_params" | grep "\\$i" >> /dev/null

			#$1 have, ignore
			if [ $? -eq 0 ]; then
				new_params=""
			#$1 don`t have, add in $1
			else
				new_params="$i"
			fi
		else
			if [ "$new_params" = "" ]; then
				continue
			else
				final_params="$final_params"" ""$new_params"" ""$i"
				new_params=""
			fi
		fi			
	done	
	if [ "$new_params" != "" ]; then
		final_params="$final_params"" ""$new_params"
		new_params=""
	fi
	echo -e "$final_params"
}

set_testcases_to_list()
{
	line_count=1
	cat $1 | while read ts_line
	do
		ts_line=`echo $ts_line`
		if [ -z "$ts_line" ]; then
			continue
		fi
		
		if [ "${ts_line:0:1}" = "#" ]; then
			continue
		fi
		extra_params=""
		testcase_name=`echo "$ts_line" | awk -F '[ {]' '{print $1}'`
		if [[ "$ts_line" =~ "{" ]]; then
			extra_params=`echo $ts_line | cut -d '{' -f2|cut -d '}' -f1`
			extra_params=`echo $extra_params`
		fi
		
		if [ "$extra_params" = "" ]; then
			echo -e "\t\tcase $line_count: $testcase_name"
		else
			echo -e "\t\tcase $line_count: $testcase_name\tParams:$extra_params"
		fi
		if [ ! -z "$extra_params" ] || [ ! -z "$2" ]; then
			extra_params=`merge_params "$extra_params" "$2"`
		fi
		line_count=$(($line_count+1))
		if [ "$3" = "qemu" ] || [ "$3" = "QEMU" ]; then
			echo -e "$3"":""$testcase_name"" { ""$extra_params"" } " >> $CURRENT_CASESLIST_FILE
		fi

		if [ "$3" = "libvirt" ] || [ "$3" = "LIBVIRT" ]; then
			echo -e "$3"":""$testcase_name"" { ""$extra_params"" } " >> $CURRENT_CASESLIST_FILE
		fi	
	done
}


init_testcase_list()
{
	module_count=1

	cat $DEFAULT_MODULE_LIST | while read ml_line
	do
		ml_line=`echo $ml_line`
		if [ -z "$ml_line" ]; then
			continue
		fi

		if [ "${ml_line:0:1}" = "#" ]; then
			continue
		fi

		module_extra_params=""
		class=""
		module_name=""
		module_file=""
		class=`echo $ml_line | cut -d ':' -f1`
		module_name=`echo "$ml_line" | cut -d ':' -f2  | awk -F'[ {]' '{print $1}'`
		module_file="$DEFAULT_MODULE_FILE_DIR$class"/"$module_name"
		if [[ "$ml_line" =~ "{" ]]; then
			module_extra_params=`echo $ml_line | cut -d '{' -f2 | cut -d '}' -f1`
			module_extra_params=`echo $module_extra_params`
		fi

		if [ -z "$module_name" ]; then
			echo "ERROR: Modules name is not set($module_name)"
			exit 1
		fi
					

		if [ "$class" = "qemu" ] || [ "$class" = "QEMU" ]; then
			default_cmd=`merge_params "$QEMU_EXTRA_COMMAND" "$DEFAULT_EXTRA_COMMAND"`
			default_cmd=`merge_params "$module_extra_params" "$default_cmd"`
		elif [ "$class" = "libvirt" ] || [ "$class" = "LIBVIRT" ]; then
			default_cmd=`merge_params "$LIBVIRT_EXTRA_COMMAND" "$DEFAULT_EXTRA_COMMAND"`
			default_cmd=`merge_params "$module_extra_params" "$default_cmd"`
		else	
			echo "ERROR: Modules class is not set($module_name)"
			exit 2
		fi


		if [ "$MODE" = "DIRECT" ]; then
			echo -e "\t\tcase $module_count: $module_name $module_extra_params"
			echo -e "$class"":""$module_name"" { ""$module_extra_params"" } " >> $CURRENT_CASESLIST_FILE
		else
			printf "\tModule $module_count: %-40s\t%-60s\n" "$class:$module_name" "module_params:$module_extra_params"
			if [ ! -f "$module_file" ]; then
				echo "ERROR: Don\`t have testcases file($module_file)"
				exit 3
			else
				set_testcases_to_list "$module_file" "$default_cmd" "$class"
			fi
		fi
		module_count=$(($module_count+1))
	done
}

generate_cmd()
{
	if [ -z "$1" ]; then
		echo "1";
	fi

	if [ -z "$3" ]; then
		echo "1";
	fi
	
	cmd=""
	
	if [ "$class" = "qemu" ] || [ "$class" = "QEMU" ]; then
		cmd="$VIRTTEST_DIR""$DEFAULT_RUN_COMMAND"" ""$params"" ""--tests"" ""$testcase_name"" ""-v"
	elif [ "$class" = "libvirt" ] || [ "$class" = "LIBVIRT" ]; then
		cmd="$VIRTTEST_DIR""$DEFAULT_RUN_COMMAND"" ""$params"" ""--tests"" ""$testcase_name"" ""-v"
	else
		echo "1"
	fi	
	echo "$cmd"
}

run_test()
{
	testcase_count=1

	cat $CURRENT_CASESLIST_FILE | while read tc_line
	do
		class=""
		params=""
		testcase_name=""
		class=`echo $tc_line | cut -d ':' -f1`
		testcase_name=`echo "$tc_line" | cut -d ':' -f2  | awk -F'[ {]' '{print $1}'`
		if [[ "$tc_line" =~ "{" ]]; then
			params=`echo $tc_line | cut -d '{' -f2 | cut -d '}' -f1`
			params=`echo $params`
		fi
		printf "%-150s" "$testcase_count. $class:$testcase_name"
		run_cmd=`generate_cmd "$class" "$testcase_name" "$params"`
		if [ "$run_cmd" = "1" ]; then
			echo -e "\033[34m SKIP(autorun: Parameter error)  \033[0m"
			echo -e "SKIP\t$class:$testcase_name (autorun: Parameter error)" >> "CURRENT_LOG_FILE"
			skip_count=$(($skip_count+1))
		else
			result=`${run_cmd}  2>>"$CURRENT_DETAIL_LOG_FILE" | grep -E "PASSED|FAILED|SKIPPED"`
			PASS=`echo "$result" | grep "PASSED: " | awk -F'PASSED: ' '{print $2}'`
			FAIL=`echo "$result" | grep "FAILED: " | awk -F'FAILED: ' '{print $2}'`
			SKIP=`echo "$result" | grep "SKIPPED: " | awk -F'SKIPPED: ' '{print $2}'`
			if [ "$PASS" = "1" ]; then
				printf "\033[32m %-20s \033[0m\n" "PASS"
				echo -e "PASS\t$class:$testcase_name" >> "$CURRENT_LOG_FILE"
				pass_count=$(($pass_count+1))
			elif [ "$FAIL" = "1" ]; then
				printf "\033[31m %-20s \033[0m\n" "FAIL"
				echo -e "FAIL\t$class:$testcase_name" >> "$CURRENT_LOG_FILE"
				fail_count=$(($fail_count+1))
			elif [ "$SKIP" = "1" ]; then
				printf "\033[34m %-20s \033[0m\n" "SKIP"
				echo -e "SKIP\t$class:$testcase_name" >> "$CURRENT_LOG_FILE"
				skip_count=$(($skip_count+1))
			else
				printf "\033[31m %-20s \033[0m\n" "FAIL"
				echo -e "FAIL\t$class:$testcase_name" >> "$CURRENT_LOG_FILE"
				fail_count=$(($fail_count+1))	
			fi	
		fi
		((testcase_count++))
	done
}

init_env_params()
{
	DATE=$(date +%Y-%m-%d-%R:%S)
	CURRENT_LOG_PATH="$DEFAULT_LOG_DIR""$DATE""/"
	CURRENT_CASESLIST_FILE="$CURRENT_LOG_PATH""testcases_list"
	CURRENT_LOG_FILE="$CURRENT_LOG_PATH""log"
	CURRENT_DETAIL_LOG_FILE="$CURRENT_LOG_PATH""detail_log"
}

init_file()
{
	
	if [ ! -d "$DEFAULT_LOG_DIR" ]; then
		mkdir "$DEFAULT_LOG_DIR"
	fi
	
	if [ ! -d "$CURRENT_LOG_PATH" ]; then
		mkdir $CURRENT_LOG_PATH
	fi

	if [ ! -f "$CURRENT_CASESLIST_FILE" ]; then
		touch $CURRENT_CASESLIST_FILE
	fi

	if [ ! -f "$CURRENT_LOG_FILE" ]; then
		touch $CURRENT_LOG_FILE
	fi

	if [ ! -f "$CURRENT_DETAIL_LOG_FILE" ]; then
		touch $CURRENT_DETAIL_LOG_FILE
	fi
}

init()
{
	init_env_params
	init_file
}




main()
{
	debug
	echo -e "Testcases List:"
	init_testcase_list

	echo ""
	echo -e "Start:"
	run_test
}


usage()
{
	echo -e "Usage: runtest [Options]"
	echo -e ""
	echo -e "Options:"
	printf "\t%-40s%-20s\n" "-h" "Show this help message and exit"
	printf "\t%-40s%-20s\n" "-m <modules_list_file>" "Use custom modules_list.        Default: ./tests/modules_list"
	printf "\t%-40s%-20s\n" "-t <testcases_list_file>" "Only run testcase in this file."
	exit 0
}

# Start in here
init
while getopts "hm:t:" arg 
do
	case $arg in
		h)
			usage
			;;
		m)
			if [ ! -f "$OPTARG" ]; then
				echo -e "$OPTARG is not exist."
				exit 1
			fi
			DEFAULT_MODULE_LIST="$OPTARG"	
			;;
		t)
			if [ ! -f "$OPTARG" ]; then
				echo -e "$OPTARG is not exist."
				exit 1
			fi
			MODE="DIRECT"	
			DEFAULT_MODULE_LIST="$OPTARG"	
			;;
		?)
			echo "unkonw argument"
			usage
        		;;
        esac
done
main

